SELECT 
   CONCAT(O.NAME, '(', SUBSTR(O.OCCUPATION, 1, 1), ')')  "name_occupation"

FROM OCCUPATIONS O
ORDER BY O.NAME;

SELECT
    CONCAT('There are a total of ', OP.op_count, ' ', LOWER(OP.OCCUPATION), 's.')
FROM
(
SELECT 
    O.OCCUPATION, COUNT(O.OCCUPATION) op_count
FROM OCCUPATIONS O
GROUP BY O.OCCUPATION
) OP
ORDER BY OP.op_count, OP.OCCUPATION;